version: '3.1'
services:
  nginx:
    container_name: nginx-angular
    image: nginx-angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nest
    networks:
      - nest-mean-network

  nest:
    container_name: nest-server
    image: nest-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - nest-mongodb
    networks:
      - nest-mean-network

  nest-mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nest-mean-network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - "8080:8080"
    networks:
    - nest-mean-network

networks:
  nest-mean-network:
    driver: bridge
